/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSettingsRouteImport } from './routes/api/settings'
import { Route as ApiAiAddFeatureRouteImport } from './routes/api/ai/add-feature'
import { Route as ApiAiAnalyzeProjectRouteImport } from './routes/api/ai/analyze-project'
import { Route as ApiAiFixProjectRouteImport } from './routes/api/ai/fix-project'
import { Route as ApiAiGenerateProjectRouteImport } from './routes/api/ai/generate-project'
import { Route as ApiAiTestRouteImport } from './routes/api/ai/test'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAddFeatureRoute = ApiAiAddFeatureRouteImport.update({
  id: '/api/ai/add-feature',
  path: '/api/ai/add-feature',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAnalyzeProjectRoute = ApiAiAnalyzeProjectRouteImport.update({
  id: '/api/ai/analyze-project',
  path: '/api/ai/analyze-project',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiFixProjectRoute = ApiAiFixProjectRouteImport.update({
  id: '/api/ai/fix-project',
  path: '/api/ai/fix-project',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateProjectRoute = ApiAiGenerateProjectRouteImport.update({
  id: '/api/ai/generate-project',
  path: '/api/ai/generate-project',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTestRoute = ApiAiTestRouteImport.update({
  id: '/api/ai/test',
  path: '/api/ai/test',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/ai/add-feature': typeof ApiAiAddFeatureRoute
  '/api/ai/analyze-project': typeof ApiAiAnalyzeProjectRoute
  '/api/ai/fix-project': typeof ApiAiFixProjectRoute
  '/api/ai/generate-project': typeof ApiAiGenerateProjectRoute
  '/api/ai/test': typeof ApiAiTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/ai/add-feature': typeof ApiAiAddFeatureRoute
  '/api/ai/analyze-project': typeof ApiAiAnalyzeProjectRoute
  '/api/ai/fix-project': typeof ApiAiFixProjectRoute
  '/api/ai/generate-project': typeof ApiAiGenerateProjectRoute
  '/api/ai/test': typeof ApiAiTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/ai/add-feature': typeof ApiAiAddFeatureRoute
  '/api/ai/analyze-project': typeof ApiAiAnalyzeProjectRoute
  '/api/ai/fix-project': typeof ApiAiFixProjectRoute
  '/api/ai/generate-project': typeof ApiAiGenerateProjectRoute
  '/api/ai/test': typeof ApiAiTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/settings'
    | '/api/ai/add-feature'
    | '/api/ai/analyze-project'
    | '/api/ai/fix-project'
    | '/api/ai/generate-project'
    | '/api/ai/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/settings'
    | '/api/ai/add-feature'
    | '/api/ai/analyze-project'
    | '/api/ai/fix-project'
    | '/api/ai/generate-project'
    | '/api/ai/test'
  id:
    | '__root__'
    | '/'
    | '/api/settings'
    | '/api/ai/add-feature'
    | '/api/ai/analyze-project'
    | '/api/ai/fix-project'
    | '/api/ai/generate-project'
    | '/api/ai/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSettingsRoute: typeof ApiSettingsRoute
  ApiAiAddFeatureRoute: typeof ApiAiAddFeatureRoute
  ApiAiAnalyzeProjectRoute: typeof ApiAiAnalyzeProjectRoute
  ApiAiFixProjectRoute: typeof ApiAiFixProjectRoute
  ApiAiGenerateProjectRoute: typeof ApiAiGenerateProjectRoute
  ApiAiTestRoute: typeof ApiAiTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/add-feature': {
      id: '/api/ai/add-feature'
      path: '/api/ai/add-feature'
      fullPath: '/api/ai/add-feature'
      preLoaderRoute: typeof ApiAiAddFeatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/analyze-project': {
      id: '/api/ai/analyze-project'
      path: '/api/ai/analyze-project'
      fullPath: '/api/ai/analyze-project'
      preLoaderRoute: typeof ApiAiAnalyzeProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/fix-project': {
      id: '/api/ai/fix-project'
      path: '/api/ai/fix-project'
      fullPath: '/api/ai/fix-project'
      preLoaderRoute: typeof ApiAiFixProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate-project': {
      id: '/api/ai/generate-project'
      path: '/api/ai/generate-project'
      fullPath: '/api/ai/generate-project'
      preLoaderRoute: typeof ApiAiGenerateProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/test': {
      id: '/api/ai/test'
      path: '/api/ai/test'
      fullPath: '/api/ai/test'
      preLoaderRoute: typeof ApiAiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSettingsRoute: ApiSettingsRoute,
  ApiAiAddFeatureRoute: ApiAiAddFeatureRoute,
  ApiAiAnalyzeProjectRoute: ApiAiAnalyzeProjectRoute,
  ApiAiFixProjectRoute: ApiAiFixProjectRoute,
  ApiAiGenerateProjectRoute: ApiAiGenerateProjectRoute,
  ApiAiTestRoute: ApiAiTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
