/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExtensionRouteImport } from './routes/extension'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TelegramRouteImport } from './routes/telegram'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as ApiSettingsRouteImport } from './routes/api/settings'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ApiAiAddFeatureRouteImport } from './routes/api/ai/add-feature'
import { Route as ApiAiAnalyzeProjectRouteImport } from './routes/api/ai/analyze-project'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as ApiAiFixProjectRouteImport } from './routes/api/ai/fix-project'
import { Route as ApiAiGenerateProjectRouteImport } from './routes/api/ai/generate-project'
import { Route as ApiAiTestRouteImport } from './routes/api/ai/test'
import { Route as ApiAiValidateProjectRouteImport } from './routes/api/ai/validate-project'
import { Route as ApiProjectApplyRouteImport } from './routes/api/project/apply'
import { Route as ApiProjectUploadRouteImport } from './routes/api/project/upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionRoute = ExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TelegramRoute = TelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAddFeatureRoute = ApiAiAddFeatureRouteImport.update({
  id: '/api/ai/add-feature',
  path: '/api/ai/add-feature',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAnalyzeProjectRoute = ApiAiAnalyzeProjectRouteImport.update({
  id: '/api/ai/analyze-project',
  path: '/api/ai/analyze-project',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiFixProjectRoute = ApiAiFixProjectRouteImport.update({
  id: '/api/ai/fix-project',
  path: '/api/ai/fix-project',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateProjectRoute = ApiAiGenerateProjectRouteImport.update({
  id: '/api/ai/generate-project',
  path: '/api/ai/generate-project',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTestRoute = ApiAiTestRouteImport.update({
  id: '/api/ai/test',
  path: '/api/ai/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiValidateProjectRoute = ApiAiValidateProjectRouteImport.update({
  id: '/api/ai/validate-project',
  path: '/api/ai/validate-project',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectApplyRoute = ApiProjectApplyRouteImport.update({
  id: '/api/project/apply',
  path: '/api/project/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectUploadRoute = ApiProjectUploadRouteImport.update({
  id: '/api/project/upload',
  path: '/api/project/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/extension': typeof ExtensionRoute
  '/settings': typeof SettingsRoute
  '/telegram': typeof TelegramRoute
  '/upload': typeof UploadRoute
  '/whatsapp': typeof WhatsappRoute
  '/api/settings': typeof ApiSettingsRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/ai/add-feature': typeof ApiAiAddFeatureRoute
  '/api/ai/analyze-project': typeof ApiAiAnalyzeProjectRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/fix-project': typeof ApiAiFixProjectRoute
  '/api/ai/generate-project': typeof ApiAiGenerateProjectRoute
  '/api/ai/test': typeof ApiAiTestRoute
  '/api/ai/validate-project': typeof ApiAiValidateProjectRoute
  '/api/project/apply': typeof ApiProjectApplyRoute
  '/api/project/upload': typeof ApiProjectUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/extension': typeof ExtensionRoute
  '/settings': typeof SettingsRoute
  '/telegram': typeof TelegramRoute
  '/upload': typeof UploadRoute
  '/whatsapp': typeof WhatsappRoute
  '/api/settings': typeof ApiSettingsRoute
  '/projects': typeof ProjectsIndexRoute
  '/api/ai/add-feature': typeof ApiAiAddFeatureRoute
  '/api/ai/analyze-project': typeof ApiAiAnalyzeProjectRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/fix-project': typeof ApiAiFixProjectRoute
  '/api/ai/generate-project': typeof ApiAiGenerateProjectRoute
  '/api/ai/test': typeof ApiAiTestRoute
  '/api/ai/validate-project': typeof ApiAiValidateProjectRoute
  '/api/project/apply': typeof ApiProjectApplyRoute
  '/api/project/upload': typeof ApiProjectUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/extension': typeof ExtensionRoute
  '/settings': typeof SettingsRoute
  '/telegram': typeof TelegramRoute
  '/upload': typeof UploadRoute
  '/whatsapp': typeof WhatsappRoute
  '/api/settings': typeof ApiSettingsRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/ai/add-feature': typeof ApiAiAddFeatureRoute
  '/api/ai/analyze-project': typeof ApiAiAnalyzeProjectRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/fix-project': typeof ApiAiFixProjectRoute
  '/api/ai/generate-project': typeof ApiAiGenerateProjectRoute
  '/api/ai/test': typeof ApiAiTestRoute
  '/api/ai/validate-project': typeof ApiAiValidateProjectRoute
  '/api/project/apply': typeof ApiProjectApplyRoute
  '/api/project/upload': typeof ApiProjectUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/extension'
    | '/settings'
    | '/telegram'
    | '/upload'
    | '/whatsapp'
    | '/api/settings'
    | '/projects/'
    | '/api/ai/add-feature'
    | '/api/ai/analyze-project'
    | '/api/ai/chat'
    | '/api/ai/fix-project'
    | '/api/ai/generate-project'
    | '/api/ai/test'
    | '/api/ai/validate-project'
    | '/api/project/apply'
    | '/api/project/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/extension'
    | '/settings'
    | '/telegram'
    | '/upload'
    | '/whatsapp'
    | '/api/settings'
    | '/projects'
    | '/api/ai/add-feature'
    | '/api/ai/analyze-project'
    | '/api/ai/chat'
    | '/api/ai/fix-project'
    | '/api/ai/generate-project'
    | '/api/ai/test'
    | '/api/ai/validate-project'
    | '/api/project/apply'
    | '/api/project/upload'
  id:
    | '__root__'
    | '/'
    | '/extension'
    | '/settings'
    | '/telegram'
    | '/upload'
    | '/whatsapp'
    | '/api/settings'
    | '/projects/'
    | '/api/ai/add-feature'
    | '/api/ai/analyze-project'
    | '/api/ai/chat'
    | '/api/ai/fix-project'
    | '/api/ai/generate-project'
    | '/api/ai/test'
    | '/api/ai/validate-project'
    | '/api/project/apply'
    | '/api/project/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExtensionRoute: typeof ExtensionRoute
  SettingsRoute: typeof SettingsRoute
  TelegramRoute: typeof TelegramRoute
  UploadRoute: typeof UploadRoute
  WhatsappRoute: typeof WhatsappRoute
  ApiSettingsRoute: typeof ApiSettingsRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiAiAddFeatureRoute: typeof ApiAiAddFeatureRoute
  ApiAiAnalyzeProjectRoute: typeof ApiAiAnalyzeProjectRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiFixProjectRoute: typeof ApiAiFixProjectRoute
  ApiAiGenerateProjectRoute: typeof ApiAiGenerateProjectRoute
  ApiAiTestRoute: typeof ApiAiTestRoute
  ApiAiValidateProjectRoute: typeof ApiAiValidateProjectRoute
  ApiProjectApplyRoute: typeof ApiProjectApplyRoute
  ApiProjectUploadRoute: typeof ApiProjectUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension': {
      id: '/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof ExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telegram': {
      id: '/telegram'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof TelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/add-feature': {
      id: '/api/ai/add-feature'
      path: '/api/ai/add-feature'
      fullPath: '/api/ai/add-feature'
      preLoaderRoute: typeof ApiAiAddFeatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/analyze-project': {
      id: '/api/ai/analyze-project'
      path: '/api/ai/analyze-project'
      fullPath: '/api/ai/analyze-project'
      preLoaderRoute: typeof ApiAiAnalyzeProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/fix-project': {
      id: '/api/ai/fix-project'
      path: '/api/ai/fix-project'
      fullPath: '/api/ai/fix-project'
      preLoaderRoute: typeof ApiAiFixProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate-project': {
      id: '/api/ai/generate-project'
      path: '/api/ai/generate-project'
      fullPath: '/api/ai/generate-project'
      preLoaderRoute: typeof ApiAiGenerateProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/test': {
      id: '/api/ai/test'
      path: '/api/ai/test'
      fullPath: '/api/ai/test'
      preLoaderRoute: typeof ApiAiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/validate-project': {
      id: '/api/ai/validate-project'
      path: '/api/ai/validate-project'
      fullPath: '/api/ai/validate-project'
      preLoaderRoute: typeof ApiAiValidateProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/project/apply': {
      id: '/api/project/apply'
      path: '/api/project/apply'
      fullPath: '/api/project/apply'
      preLoaderRoute: typeof ApiProjectApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/project/upload': {
      id: '/api/project/upload'
      path: '/api/project/upload'
      fullPath: '/api/project/upload'
      preLoaderRoute: typeof ApiProjectUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExtensionRoute: ExtensionRoute,
  SettingsRoute: SettingsRoute,
  TelegramRoute: TelegramRoute,
  UploadRoute: UploadRoute,
  WhatsappRoute: WhatsappRoute,
  ApiSettingsRoute: ApiSettingsRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiAiAddFeatureRoute: ApiAiAddFeatureRoute,
  ApiAiAnalyzeProjectRoute: ApiAiAnalyzeProjectRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiFixProjectRoute: ApiAiFixProjectRoute,
  ApiAiGenerateProjectRoute: ApiAiGenerateProjectRoute,
  ApiAiTestRoute: ApiAiTestRoute,
  ApiAiValidateProjectRoute: ApiAiValidateProjectRoute,
  ApiProjectApplyRoute: ApiProjectApplyRoute,
  ApiProjectUploadRoute: ApiProjectUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
